### ISSUE TITLE
Add GOTESTS_TEMPLATE and GOTESTS_TEMPLATE_DIR environment variables

### ISSUE THREAD

**Issue by shihanng** [cweill/gotests#116]
What do you think about adding `GOTESTS_TEMPLATE` and `GOTESTS_TEMPLATE_DIR` environment variables that corresponds to the `-template` and `-template_dir` options?

When working with different projects, some might being using testing framework like https://github.com/stretchr/testify some might not. Having these environment variables available allows users to which between the template types easily especially when using it together with tool like https://github.com/direnv/direnv that can load/unload environment variables depending on the working directory.

Maybe what we can do is allow user to set the `template` or `template_dir` values via both flags and environment variables with the value of the flag takes precedence over the one from environment variables.

I can create a PR if you think this is okay.

**Comment by cweill** [comment]
@shihanng I think that's a very reasonable proposal. Feel free to send a PR.
