### ISSUE TITLE
Namespacing in the test table

### ISSUE THREAD

**Issue by thomaso-mirodin** [cweill/gotests#15]
Hey :D

Thanks a bunch this has been really useful in the past few days. Have you thought about trying to namespace the different arguments in the table. For example a sample s3 mock:

```go
package main

import "fmt"

type S3Bucket struct {
	Name    string
	Storage map[string][]byte
}

func (s *S3Bucket) Save(name string, body []byte) error {
	if err := validateName(name); err != nil {
		return err
	}

	s.Storage[name] = body
	return nil
}

func validateName(name string) error {
	if len(name) == 0 {
		return fmt.Errorf("name must not be empty")
	}

	return nil
}
```

will produce this test:

```go
func TestS3BucketSave(t *testing.T) {
	tests := []struct {
		name    string
		fname   string
		storage map[string][]byte
		pname   string
		body    []byte
		wantErr bool
	}{
	// TODO: Add test cases.
	}
	for _, tt := range tests {
		s := &S3Bucket{
			Name:    tt.fname,
			Storage: tt.storage,
		}
		if err := s.Save(tt.pname, tt.body); (err != nil) != tt.wantErr {
			t.Errorf("%q. S3Bucket.Save() error = %v, wantErr %v", tt.name, err, tt.wantErr)
		}
	}
}
```

but since the tests struct includes both the fields and arguments it can get a bit confusing trying mentally keep track of where things going. Would you consider doing something like this instead?

```go
func TestS3BucketSave(t *testing.T) {
	tests := []struct {
		fields struct {
			name string
			body []byte
		}
		args struct {
			name    string
			storage map[string][]byte
		}
		name    string
		wantErr bool
	}{
	// TODO: Add test cases.
	}
	for _, tt := range tests {
		s := &S3Bucket{
			Name:    tt.fields.name,
			Storage: tt.fields.storage,
		}
		if err := s.Save(tt.args.pname, tt.args.body); (err != nil) != tt.wantErr {
			t.Errorf("%q. S3Bucket.Save() error = %v, wantErr %v", tt.name, err, tt.wantErr)
		}
	}
}
```

**Comment by cweill** [comment]
Glad to hear you're finding gotests useful. :)

That's actually a great suggestions! I was considering just putting comments like:

```go
func TestS3BucketSave(t *testing.T) {
    tests := []struct {
        name    string
        // Fields.
        fname   string
        storage map[string][]byte
        // Parameters.
        pname   string
        body    []byte
        // Results.
        wantErr bool
    }{
    // TODO: Add test cases.
    }
    for _, tt := range tests {
        s := &S3Bucket{
            Name:    tt.fname,
            Storage: tt.storage,
        }
        if err := s.Save(tt.pname, tt.body); (err != nil) != tt.wantErr {
            t.Errorf("%q. S3Bucket.Save() error = %v, wantErr %v", tt.name, err, tt.wantErr)
        }
    }
}
```

But your suggestion would eliminate the namespacing hack I use (pname vs. fname). I'll need to think about the implementation some more, and of any edge cases. At first glance, it sounds reasonable.

**Comment by cweill** [comment]
On second thought, there are some issues with using structs to namespace different arguments, particularly when writing test cases:

1. If the developer omits one of the structs, they'll get a nil-dereference runtime error from the test code, not the code under test. No fun.
1. It requires extra work for each test case to create a new struct.

Instead, __gotests__ could do the following: 

1. Prefix an `r` to every receiver field
1. Leave parameter names as they are
1. Namespace the test name in case of conflict

Consider:

```go
func TestS3BucketSave(t *testing.T) {
    tests := []struct {
        tname    string
        rName    string
        rStorage map[string][]byte
        name     string
        body     []byte
        wantErr  bool
    }{
    // TODO: Add test cases.
    }
    for _, tt := range tests {
        s := &S3Bucket{
            Name:    tt.rName,
            Storage: tt.rStorage,
        }
        if err := s.Save(tt.name, tt.body); (err != nil) != tt.wantErr {
            t.Errorf("%q. S3Bucket.Save() error = %v, wantErr %v", tt.tname, err, tt.wantErr)
        }
    }
}
```

**Comment by thomaso-mirodin** [comment]
My goal is just understandability. :D

Prefixing each with something as well as including the comments in the example you had earlier would probably accomplish that goal.

**Comment by cweill** [comment]
On second thought, I prefer your suggestion with the structs. I'm not a big fan of the comments, and the prefix name-spacing is kind of confusing (rName vs pName).
