### ISSUE TITLE
Support for specifying an expected error in the table

### ISSUE THREAD

**Issue by thomaso-mirodin** [cweill/gotests#16]
It would also be really useful if you could specify a specific error value that should be returned by a test, rather than the general `wantErr`.

For example extending #15's example

```go
package main

import "fmt"

type S3Bucket struct {
	Name    string
	Storage map[string][]byte
}

func (s *S3Bucket) Save(name string, body []byte) error {
	if err := validateName(name); err != nil {
		return err
	}

	if err := validateBody(body); err != nil {
		return err
	}

	s.Storage[name] = body
	return nil
}

func validateName(name string) error {
	if len(name) == 0 {
		return fmt.Errorf("name must not be empty")
	}

	return nil
}

const MAX_BODY_SIZE = 1024

func validateBody(body []byte) error {
	if len(body) > MAX_BODY_SIZE {
		return fmt.Errorf("contents are too large (>%d bytes)", MAX_BODY_SIZE)
	}

	return nil
}

```

would produce:

```go
func TestS3BucketSave(t *testing.T) {
	tests := []struct {
		name    string
		fname   string
		storage map[string][]byte
		pname   string
		body    []byte
		wantErr bool
	}{
	// TODO: Add test cases.
	}
	for _, tt := range tests {
		s := &S3Bucket{
			Name:    tt.fname,
			Storage: tt.storage,
		}
		if err := s.Save(tt.pname, tt.body); (err != nil) != tt.wantErr {
			t.Errorf("%q. S3Bucket.Save() error = %v, wantErr %v", tt.name, err, tt.wantErr)
		}
	}
}
```

It'd be nice if I could test for the different error cases :D

**Comment by cweill** [comment]
I intentionally reduced the error-result check to a boolean in order to encourage testing error semantics, not error messages. The issue, especially when using `fmt.Errorf`, is that this makes tests brittle if you ever change the error down the line. String comparison on error messages has the potential of transforming tests into change detectors, so I think simply checking whether an error is returned is the best choice.

**Comment by thomaso-mirodin** [comment]
Yeah, I can definitely understand that situation as I've experienced it myself :D

+ it isn't like I can't easily change it when I want it :P

**Comment by cweill** [comment]
> it isn't like I can't easily change it when I want it :P

You got it. ;)

In any case, thanks for the FRs!

**Comment by cvigo** [comment]
I was missing the same feature when I found this enhancement request.
To my understanding, proper error reporting is crucial in API development and several other scenarios. Copy/Paste often makes your API returning wrong errors that make your API consumers life harder if they reach production. Typical "Not Found"  when you should have said "Not Authorised". Therefore, checking specific error reporting is a good practice in many scenarios.
