### ISSUE TITLE
How to generate named tests?

### ISSUE THREAD

**Issue by jurisbu** [cweill/gotests#177]
Hi,

How to generate named tests using map instead of slice? Doing a bit of archeology there seems to be support for this as part of #148. But how one can enable it from commandline? I cannot find any examples, or help or reference information. Passing `-named` does not work.

Would be great to add some help with examples?

gotests v1.6.0

cc @butuzov

**Comment by jurisbu** [comment]
OK, seems that the code that implements `-named` functionality has not been released, meaning it is still in `develop` branch. 
@cweill Can we expect v1.7.0 release at some point? :pray: Otherwise `go install ...gotests@latest` pulls in v1.6.0.

**Comment by butuzov** [comment]
Well you can just pick dev branch, it’s actually stable. At least it was 9
month ago. @cweill is/was pretty busy at that moment to release changes
from develop branch.

**Comment by jurisbu** [comment]
@butuzov Yes that is one way, just have to remember when updating all Go tools from VS Code Go extension that I need to manually update `gotests`, since VS Code Go extension will update tools to `@latest`. A little inconvenience. Oh, well.

**Comment by butuzov** [comment]
If you specify path to go tests located elsewhere, viscose updating to @latest wouldn't affect your setup. It's possible with vscode extension.

**Comment by stevenh** [comment]
This is still causing an issue, any info when a version with -named will be released?

**Comment by butuzov** [comment]
@cweill good question. Charles, can we have it?

**Comment by ysomad** [comment]
Would be great, any updates on this?
