### ISSUE TITLE
`go install github.com/cweill/gotests@v1.6.0`: package github.com/cweill/gotests is not a main package

### ISSUE THREAD

**Issue by cold-bin** [cweill/gotests#189]
`go install github.com/cweill/gotests/gotests@v1.6.0` is good

**Comment by jabielecki** [comment]
Unclear. Is there any place in the documentation that suggested this command? Or are you suggesting a nice-to-have?

**Comment by double12gzh** [comment]
Per installation in README.md ` go get -u github.com/cweill/gotests/...`  works well for me. First, I need to change into the project, where `go.mod` is placed. Then run command ` go get -u github.com/cweill/gotests/...` .

But there is only a tiny problem, after run the command, the `gotests` still cannot be found in `GOBIN` or `GOPATH` or `PATH`, I have no choice but clone the gotests repository and build the `gotests` bin locally

**Comment by cold-bin** [comment]
> Unclear. Is there any place in the documentation that suggested this command? Or are you suggesting a nice-to-have?

I want to say that I can download a definitive version using the way
