### ISSUE TITLE
Atom Editor Plugin

### ISSUE THREAD

**Issue by jcmartins** [cweill/gotests#19]
Hi,
do you have plans to make a Atom Plugin?

tks

**Comment by cweill** [comment]
No plans yet, though contributions are certainly welcome.

**Comment by abulimov** [comment]
I'm using your excellent gotests utility with Atom, and made a simple plugin for it - https://atom.io/packages/gotests. It resembles the Sublime Text plugin functionality. Hope it helps!

**Comment by cweill** [comment]
Thanks! I'll like to your plugin in the README.
