### ISSUE TITLE
generate tests failing after upgraded to go1.7

### ISSUE THREAD

**Issue by sudheernayudu** [cweill/gotests#25]
Hi,
I'm getting the below error while generating tests after upgraded to go1.7. If anything is missing, please help..

panic: inconsistent import:
    func errors.New(text string) error
previously imported as:
    func errors.New(text string) error
 [recovered]
    panic: inconsistent import:
    func errors.New(text string) error
previously imported as:
    func errors.New(text string) error

goroutine 34 [running]:
panic(0x28f460, 0xc4204c94c0)
    /usr/local/go/src/runtime/panic.go:500 +0x1a1
go/types.(_Checker).handleBailout(0xc4202861c0, 0xc4202f5a18)
    /usr/local/go/src/go/types/check.go:213 +0xae
panic(0x28f460, 0xc4204c94c0)
    /usr/local/go/src/runtime/panic.go:458 +0x243
go/internal/gcimporter.(_importer).declare(0xc42036f380, 0x49aba0, 0xc4204fdf90)
    /usr/local/go/src/go/internal/gcimporter/bimport.go:175 +0x17c
go/internal/gcimporter.(_importer).obj(0xc42036f380, 0xfffffffffffffffb)
    /usr/local/go/src/go/internal/gcimporter/bimport.go:203 +0x4a2
go/internal/gcimporter.BImportData(0xc420268690, 0xc4204a9000, 0xb51, 0xe00, 0xc4202ec999, 0x6, 0x0, 0x6, 0xc42005c820, 0xc42005c8f0)
    /usr/local/go/src/go/internal/gcimporter/bimport.go:88 +0x390
go/internal/gcimporter.Import(0xc420268690, 0xc4202ec999, 0x6, 0xc420288180, 0x3f, 0xc420146a00, 0x0, 0x0)
    /usr/local/go/src/go/internal/gcimporter/gcimporter.go:166 +0x551
go/importer.gcimports.ImportFrom(0xc420268690, 0xc4202ec999, 0x6, 0xc420288180, 0x3f, 0x0, 0x1, 0x2, 0x0)
    /usr/local/go/src/go/importer/importer.go:70 +0x67
go/types.(_Checker).collectObjects(0xc4202861c0)
    /usr/local/go/src/go/types/resolver.go:191 +0x826
go/types.(_Checker).checkFiles(0xc4202861c0, 0xc4204b6300, 0x16, 0x20, 0x0, 0x0)
    /usr/local/go/src/go/types/check.go:225 +0xaa
go/types.(_Checker).Files(0xc4202861c0, 0xc4204b6300, 0x16, 0x20, 0xc4204d0b70, 0xc4202f5a90)
    /usr/local/go/src/go/types/check.go:218 +0x49
go/types.(_Config).Check(0xc4204cdac0, 0x0, 0x0, 0xc42007f040, 0xc4204b6300, 0x16, 0x20, 0xc4204d4320, 0x0, 0x3, ...)
    /usr/local/go/src/go/types/api.go:344 +0x1a3
github.com/cweill/gotests/internal/goparser.(_Parser).parseTypes(0xc4202f5eb8, 0xc42007f040, 0xc4204b6300, 0x16, 0x20, 0xc4204a1e00, 0x8)
    /Users/cfs426/workspace/src/github.com/cweill/gotests/internal/goparser/goparser.go:119 +0x18c
github.com/cweill/gotests/internal/goparser.(_Parser).parseFunctions(0xc4202f5eb8, 0xc42007f040, 0xc4200b1080, 0xc4204b6300, 0x16, 0x20, 0x1e98, 0x16, 0x20)
    /Users/cfs426/workspace/src/github.com/cweill/gotests/internal/goparser/goparser.go:96 +0x74
github.com/cweill/gotests/internal/goparser.(_Parser).Parse(0xc4202f5eb8, 0xc4202880c0, 0x5b, 0xc42025a600, 0x16, 0x20, 0xc420070d80, 0x20, 0x18)
    /Users/cfs426/workspace/src/github.com/cweill/gotests/internal/goparser/goparser.go:56 +0x2b9
github.com/cweill/gotests.generateTest(0xc4202880c0, 0x5b, 0xc42025a600, 0x16, 0x20, 0xc420230880, 0x0, 0x0, 0x0)
    /Users/cfs426/workspace/src/github.com/cweill/gotests/gotests.go:100 +0xc3
github.com/cweill/gotests.parallelize.func1(0xc42022a730, 0xc42025a600, 0x16, 0x20, 0xc420230880, 0xc4202896e0, 0xc4202880c0, 0x5b)
    /Users/cfs426/workspace/src/github.com/cweill/gotests/gotests.go:72 +0xd0
created by github.com/cweill/gotests.parallelize
    /Users/cfs426/workspace/src/github.com/cweill/gotests/gotests.go:74 +0x140

**Comment by cweill** [comment]
Ack. I'll look into this when I get home. 

In the meantime, have you tried reinstalling gotests with `$ go get -u github.com/cweill/gotests/...` ?

**Comment by sudheernayudu** [comment]
I tried that too, no luck

**Comment by cweill** [comment]
Which version of Go are you running? I haven't seen this issue on Go v1.7rc3. What environment (Mac, Linux, Windows)? Can you show me the function signature that is giving you this error and steps to reproduce?

**Comment by sudheernayudu** [comment]
I tried with go1.7.1, will provide more details after i reached home. Its failing for even simple functions. Are you not getting this issue?

**Comment by cweill** [comment]
I haven't been able to reproduce it yet, but I haven't tried with Go 1.7.1. Are you on Linux?

**Comment by sudheernayudu** [comment]
I'm on mac OS x El captain

**Comment by cweill** [comment]
Can you please list the exact steps to reproduce this error including the function signature it failed on?

**Comment by cweill** [comment]
Looks like there is an issue with the `golang.org/x/tools/imports` package. Try deleting `golang.org/x/tools/imports` and then running `go get -u golang.org/x/tools/imports` again. Maybe that will help. It may have broken with go 1.7.

**Comment by itsjamie** [comment]
@sudheernayudu If you've updated your Go, I've always had the best luck with these odd errors by just removing the contents of the `pkg` directory in `$GOPATH`. If it does fix the issue for you, I think you're supposed to report it on the Go project.
