### ISSUE TITLE
Go 1.7 install failed

### ISSUE THREAD

**Issue by micyee** [cweill/gotests#27]
go get -u -v github.com/cweill/gotests/...
github.com/cweill/gotests (download)
# cd /Users/Project/go/src/github.com/cweill/gotests; git pull --ff-only

There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

```
git pull <remote> <branch>
```

If you wish to set tracking information for this branch you can do so with:

```
git branch --set-upstream-to=origin/<branch> master
```

package github.com/cweill/gotests/...: exit status 1

**Comment by cweill** [comment]
Did you try running `gotests` from the command line? Did it not work? Nothing in this error message makes it sound like the installation failed.

**Comment by micyee** [comment]
I did not find out where the problem was，But it's ok now.Thanks for answering

**Comment by cweill** [comment]
No problem. Glad to hear it worked out.

**Comment by gertcuykens** [comment]
Hmm, I get this error on OSX?

```
% go get -u -v github.com/cweill/gotests/...
github.com/cweill/gotests (download)
Fetching https://golang.org/x/tools/imports?go-get=1
Parsing meta tags from https://golang.org/x/tools/imports?go-get=1 (status code 200)
get "golang.org/x/tools/imports": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/imports?go-get=1
get "golang.org/x/tools/imports": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools?go-get=1
Parsing meta tags from https://golang.org/x/tools?go-get=1 (status code 200)
golang.org/x/tools (download)
# cd /Users/gert/go/src/golang.org/x/tools; git pull --ff-only
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

package golang.org/x/tools/imports: exit status 1
% 
```

**Comment by cweill** [comment]
Try deleting `$GOPATH/src/github.com/cweill/gotests` and `$GOPATH/bin/gotests`, then rerun the command.

**Comment by gertcuykens** [comment]
Nope same thing, ps i never get a `gotests` bin only the download.

Are you online now? the i can show you join.me/gert.cuykens

**Comment by cweill** [comment]
Check that `/Users/gert/go/src/golang.org/x/tools` exists. If it does, `cd` into `/Users/gert/go/src/github.com/cweill/gotests` and run `go install ./...`

**Comment by gertcuykens** [comment]
Yep doing it that way worked

**Comment by cweill** [comment]
Glad to hear it worked. Still,  it's strange that installing `golang.org/x/tools/goimports` is causing issues for some people.

**Comment by gertcuykens** [comment]
Do you have a mac? I think it can be easily reproducible on OSX

**Comment by gertcuykens** [comment]
```go env
GOARCH="amd64"
GOBIN="/Users/gert/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/gert/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.7.1/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.7.1/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/dv/8tlwvjr91zjdyq4rk14lkkfm0000gn/T/go-build584711619=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"```

**Comment by gertcuykens** [comment]
remove `golang.org/x/tools/` to fix the above
