### ISSUE TITLE
Testing sql.DB usage

### ISSUE THREAD

**Issue by itsjamie** [cweill/gotests#29]
Similar to #14, when `sql.DB` is detected as one of the arguments to the function or as a struct fields, perhaps the https://github.com/DATA-DOG/go-sqlmock could be included to provide a mock database connection?

**Comment by cweill** [comment]
I would prefer to avoid having third-party dependencies when generating tests. However I would like to have a way for someone to define their own "templates" for handling special scenarios like the one you mentioned.

**Comment by baixiaoshi** [comment]
how to resolve this problem
