### ISSUE TITLE
gotests will removed license header & Neovim integration

### ISSUE THREAD

**Issue by zchee** [cweill/gotests#37]
Hi,
Thanks for good tools, I always use it when writing tests.

And, I am developing gotests Neovim integration on the [zchee/nvim-go](https://github.com/zchee/nvim-go). Thanks again.

---

BTW, gotests will remove license header if already exists `*_test.go` file.
I thought doing pull request, but maybe reads the gotests code seemed to take a while, so I wanted to hear it first.
Do you have any idea?

like,

before code:

- foo.go
```go
// Copyright 2016 Koichi Shiraishi. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package foo

import "fmt"

func Foo(bar string) string {
	return fmt.Sprint(bar)
}
```

- foo_test.go
```go
// Copyright 2016 Koichi Shiraishi. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package foo

import "testing"

func TestFoo(t *testing.T) {
	type args struct {
		bar string
	}
	tests := []struct {
		name string
		args args
		want string
	}{
		{
			name: "foo test",
			args: args{bar: "barbar"},
			want: "barbar",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := Foo(tt.args.bar); got != tt.want {
				t.Errorf("Foo() = %v, want %v", got, tt.want)
			}
		})
	}
}
```

After that, adding `Baz` function to `foo.go`.

after code:

- foo.go
```go
// Copyright 2016 Koichi Shiraishi. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package foo

import "fmt"

func Foo(bar string) string {
	return fmt.Sprint(bar)
}

func Baz(i int) string {
	return strconv.Atoi(i)
}
```

run the `gotests -all -w foo.go`.
generated and auto-inserted `foo_test.go` code will removed license header.

- foo_test.go
```go
package foo

import "testing"

func TestFoo(t *testing.T) {
	type args struct {
		bar string
	}
	tests := []struct {
		name string
		args args
		want string
	}{
		{
			name: "foo test",
			args: args{bar: "barbar"},
			want: "barbar",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := Foo(tt.args.bar); got != tt.want {
				t.Errorf("Foo() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestBaz(t *testing.T) {
	type args struct {
		i int
	}
	tests := []struct {
		name string
		args args
		want string
	}{
	// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := Baz(tt.args.i); got != tt.want {
				t.Errorf("Baz() = %v, want %v", got, tt.want)
			}
		})
	}
}
```

**Comment by zchee** [comment]
I'm vendoring gotests package and use the exported API on nvim-go.
So I can parses license header before running the gotests, and re-insert to generated buffer.

However, I thought that this problem would happen to normal(on command-line) users, so I posted an issue.

**Comment by cweill** [comment]
Thank you for filing this issue. Indeed, that can be an issue if the top comments are being discarded in the test file. I don't think the fix should be too difficult, so I'll look into it.

**Comment by zchee** [comment]
@cweill Thanks quickly.
The license header is important even test file. I hope it will be fixed.
Thanks!
