### ISSUE TITLE
Test document creation error output.Process:imports.Process:...

### ISSUE THREAD

**Issue by julianfrank** [cweill/gotests#56]
Everything was working fine till yesterday but today I'm getting this error whenever I try to create a test for the function in vscode 1.19.1 windows x64
output.Process: imports.Process: C:\Users\Johan\AppData\Local\Temp\gotests_174054079:18:1: expected declaration, found ')'

In the temp folder I only see empty 0 bytes gotests_xxx files

No idea what is the problem

**Comment by julianfrank** [comment]
I stopped working on windows and now use Ubuntu... same code works without any problem in ubuntu!

**Comment by kaskavalci** [comment]
For me it was the commented out import statement in test file. Removing it fixed the problem.

```go 
import (
	// . "github.com/smartystreets/goconvey/convey"
)
```
