### ISSUE TITLE
Error while run on directory whith dot symbol (like "repo.git") in name

### ISSUE THREAD

**Issue by stdatiks** [cweill/gotests#58]
**directory**: `GOPATH/src/repo.git`
**cmd**: `gotests -all GOPATH/src/repo.git/file.go`
**output**: `input.Files: no Go source files found at GOPATH/src/repo.git`
Where GOPATH is my $GOPATH

I think that problem is here:
https://github.com/cweill/gotests/blob/651680c71b22b1164ee36398b009b2da5839e694/internal/input/input.go#L17
It should be used method `FileStat.IsDir()`

Sorry for my english =)

**Comment by cweill** [comment]
Feel free to issue a pull request.
