### ISSUE TITLE
package golang.org/x/tools/imports move to godoc.org/golang.org/x/tools/imports

### ISSUE THREAD

**Issue by wangliyao** [cweill/gotests#91]
when I run `go get -u -v github.com/cweill/gotests/...`  found this error 
> package golang.org/x/tools/imports: unrecognized import path "golang.org/x/tools/imports" (https fetch: Get https://golang.org/x/tools/imports?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)

I try open the url then find the address jump to [godoc.org/golang.org/x/tools/imports](godoc.org/golang.org/x/tools/imports)

**Comment by cweill** [comment]
Is this still an issue? I am unable to reproduce it.

**Comment by bitfishxyz** [comment]
Still have same problem @cweill .

I come from China and Great Fire Wall just block goland.org, I am not sure if this is the problem.

I already use a VNN and able to visit golang.org

From @wangliyao's id, I think he cames from China too. ...
